# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.utils.bigdata


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('object_id', models.BigIntegerField(db_index=True, verbose_name='Object id')),
                ('id', share.utils.bigdata.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggit_taggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggit_taggeditem_items', to='taggit.Tag')),
            ],
            options={
                'verbose_name_plural': 'Tagged Items',
                'verbose_name': 'Tagged Item',
            },
        ),
        migrations.AlterIndexTogether(
            name='taggeditem',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
